#!/bin/bash

commit_msg="${2}"

if [[ ! -d "${gitco_dir}" ]]; then echo "Error! Invalid 'gitco' directory."; exit 1; fi

node ${gitco_dir}/types_menu

commit_type=`cat ${gitco_dir}/cnf/type.log`

if [[ -z "${commit_type}" ]]; then echo "Error! Invalid commit type."; exit 1; fi

if [[ -z "${gitco_pattern}" ]]; then
    gitco_pattern_separator="* - type: *"
fi

pattern=${gitco_pattern//\*/}
pattern=${pattern//type/${commit_type}}

shopt -s extglob;
case "${gitco_pattern}" in
    \*!(\*)type!(\*)\*) # Matches => {*...type...*}
        echo "third case"
        if [[ -z "${gitco_pattern_separator}" ]]; then echo "Error! empty separator."; exit 1; fi
        edited_commit_msg="${commit_msg%%${gitco_pattern_separator}*}${pattern}${commit_msg##*${gitco_pattern_separator}}"
    ;;
    \*!(\*)type!(\*)) # Matches => {*...type...}
        echo "first case"
        edited_commit_msg="${commit_msg}${pattern}"
    ;;
    !(\*)type!(\*)\*) # Matches => {...type...*}
        echo "second case"
        edited_commit_msg="${pattern}${commit_msg}"
    ;;
    *)
        echo "Error! Invalid pattern (${gitco_pattern}) for commit message."
        exit 1
    ;;
esac
shopt -u extglob;

git commit -m "${edited_commit_msg}"
